name: Practica Github Actions 
on: [push]
jobs:

  linterJob:

    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  run: npm install
      -  run: npm run lint

  cypressJob:

    runs-on: ubuntu-latest
    needs: linterJob

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      - id: cypress
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start

      - run: echo ${{ steps.cypress.outcome }} > result.txt

      - uses: actions/upload-artifact@v2
        with:
          name: result.txt
          path: result.txt